module.exports = {
  SEND_MESSAGE: 'SEND_MESSAGE',
  CREATE_WINDOW: 'CREATE_WINDOW',
  GET_WINDOW_IDS: 'GET_WINDOW_IDS',
  UPDATE_MESSAGE: 'UPDATE_MESSAGE',
  UPDATE_WINDOW_IDS: 'UPDATE_WINDOW_IDS'
}
